name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  # 1. for Github split
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  # 2. for Gitlab split
  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        package:
          -
            local_path: 'chorus'
            split_repository: 'chorus'

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: 'Pixelsprout'
          repository_name: '${{ matrix.package.split_repository }}'

          # [optional, with "github.com" as default]
          repository_host: github.com

          # ↓ the user signed under the split commit
          user_name: "braedencrankd"
          user_email: "braedenleefoster@gmail.com"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package.local_path }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: 'symplify'
          repository_name: '${{ matrix.package.split_repository }}'

          # [optional, with "github.com" as default]
          repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: "braedencrankd"
          user_email: "braedenleefoster@gmail.com"